# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  CheckoutRepo:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        repository: PoojaSapaliga/HostSwaggerUI
        ref: master
    - name: remove Directory and commit
      run: |
        # Stage the file, commit and push
        git rm -r check1
        git commit -m "removed the directory"
        git push origin master

